name: sprawozdanie
on: push
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - run: pip install scipy pint open_atmos_jupyter_utils matplotlib numpy
      - uses: actions/checkout@v4
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - run: pip install nbconvert ipykernel
      - run: python -m ipykernel install --user --name=python3
      - run: python -m nbconvert --to pdf --execute Test.ipynb --ExecutePreprocessor.kernel_name=python3
      - uses: actions/upload-artifact@v4
        with:
          path: Test.pdf