name: sprawozdanie
on: push
jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - run: pip install scipy pint open_atmos_jupyter_utils matplotlib numpy
      - uses: actions/checkout@v4
      - run: sudo app-get install texlive-xetex inkscape pandoc
      - run: pip install nbconvert
      - run: python -m nbconvert --to pdf --execute Test.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: Test.pdf